name: Build and Publish YardDocs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby environment
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2

    - name: Install Bundler and dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build YardDocs
      run: rake yard

    - name: Deploy to GitHub Pages
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git fetch --unshallow || true
        git add docs/
        git commit -m "Built Docs" 
        git push origin main -f 
